# Generated by Django 4.2.3 on 2023-12-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_psychologicalanswer_psychologicalquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='similarity_calculation_done',
            field=models.BooleanField(default=False),
        ),
    ]
