version: "3.9"

services:
  app:
    build:
      # context: ./
      context: C:/Users/PraveenBabu/Desktop/recipe_app/recipe-app-api  # Use an absolute Windows path

    ports:
      - "8000:8000"
    volumes:
      # - ./app:/app
      - C:/Users/PraveenBabu/Desktop/recipe_app/recipe-app-api/app:/app  # Use an absolute Windows path

    command: >
      sh -c "python /app/manage.py runserver 0.0.0.0:8000"