# Generated by Django 3.2.23 on 2023-12-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.EmailField(default='', max_length=225),
        ),
    ]
